[platformio]
default_envs = nanoatmega328new
src_dir = .
include_dir = .

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 9600
lib_deps =
    adafruit/Adafruit GFX Library@^1.12.3
    adafruit/Adafruit SSD1306@^2.5.15
