#ifndef CONFIG_H
#define CONFIG_H

#define BUZZER_PIN 3

#define RGB_RED_PIN 2
#define RGB_GREEN_PIN 7
#define RGB_BLUE_PIN 8

#define BTN_DECREASE_PIN 6
#define BTN_START_PIN 9
#define BTN_INCREASE_PIN 10

#define RELAY_FEED_PIN 12
#define RELAY_SUCTION_PIN 11

#define MOTOR_IN1_PIN 5
#define MOTOR_IN2_PIN 13

#define PRESSURE_SENSOR_PIN A0
#define PRESSURE_SENSOR_SIMULATION false
#define PRESSURE_SENSOR_RAW_MIN 205
#define PRESSURE_SENSOR_RAW_MAX 1023
#define PRESSURE_SENSOR_RAW_TOLERANCE 25
#define PRESSURE_SENSOR_KPA_MIN -100
#define PRESSURE_SENSOR_KPA_MAX 100

#define PRESSURE_RANGE_MIN_KPA 1
#define PRESSURE_RANGE_MAX_KPA 100
#define DEFAULT_PRESSURE_RANGE_KPA 5
#define PRESSURE_TOLERANCE_KPA 1
#define PRESSURE_ALARM_MARGIN_KPA 5

#define MAX_PHASE_TIME_MS 30000UL
#define PRESSURE_SIMULATION_STEP_MS 100UL

#endif
